USE LOGIC;
DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE(
E_ID INT PRIMARY KEY AUTO_INCREMENT,
E_NAME VARCHAR(30) NOT NULL,
JOB_DESC VARCHAR(30) DEFAULT "NOT DECIDED",
SALARY INT);
-- SELECT 
SELECT * FROM EMPLOYEE;
SELECT E_NAME, JOB_DESC FROM EMPLOYEE;
SELECT DISTINCT JOB_DESC FROM EMPLOYEE;
SELECT SALARY, SALARY/10 AS "REDUCED SALARY"
FROM EMPLOYEE;

-- WHERE 
SELECT * FROM EMPLOYEE WHERE E_ID = 5;
SELECT * FROM EMPLOYEE WHERE E_NAME = "VIJAY";
SELECT * FROM EMPLOYEE WHERE SALARY >70000;
SELECT * FROM EMPLOYEE WHERE JOB_DESC <> "HR";
SELECT * FROM EMPLOYEE WHERE JOB_DESC != "HR";
SELECT * FROM EMPLOYEE WHERE HIRED_DATE = "2023-09-11";

-- AND OR NOT 
SELECT * FROM EMPLOYEE 
WHERE SALARY >=50000 AND SALARY <=100000;
SELECT * FROM EMPLOYEE 
WHERE E_NAME ="VIGNESH" AND SALARY <=40000;
SELECT * FROM EMPLOYEE 
WHERE JOB_DESC ="ANALYST" AND SALARY >=40000;
SELECT * FROM EMPLOYEE 
WHERE JOB_DESC ="ANALYST" OR SALARY >=500000;
SELECT * FROM EMPLOYEE 
WHERE JOB_DESC ="ANALYST" OR SALARY >=20000 AND E_NAME = "VIGNESH";
SELECT * FROM EMPLOYEE 
WHERE JOB_DESC ="ANALYST" OR SALARY >=500000;
SELECT * FROM EMPLOYEE 
WHERE NOT (JOB_DESC ="ANALYST" OR SALARY >=500000);
SELECT * FROM EMPLOYEE WHERE HIRED_DATE = "2023-09-11" AND HIRED_DATE = "2022-05-14";

-- IN NOT IN
SELECT *FROM EMPLOYEE
WHERE E_NAME = "AJITH" OR E_NAME = "SURYA";
SELECT * FROM EMPLOYEE
WHERE E_NAME IN ("AJITH","SURYA","SIVA");
SELECT * FROM EMPLOYEE
WHERE JOB_DESC  NOT IN ("ANALYST","CEO","MANAGER", "HR","ADMIN");

-- BETWEEN
SELECT * FROM EMPLOYEE WHERE SALARY BETWEEN 70000 AND 300000;

-- LIKE
SELECT * FROM EMPLOYEE 
WHERE E_NAME LIKE "AJ%";
SELECT * FROM EMPLOYEE 
WHERE JOB_DESC LIKE "AD%";
SELECT * FROM EMPLOYEE 
WHERE E_NAME LIKE "%RA%";
SELECT * FROM EMPLOYEE 
WHERE JOB_DESC LIKE "%E%";
SELECT * FROM EMPLOYEE 
WHERE E_NAME LIKE "___I";
SELECT * FROM EMPLOYEE 
WHERE E_NAME LIKE "VI__E__";

-- INSERT INTO EMPLOYEE (HIRED_DATE) VALUES ("2023-09-11");
-- ADD NEW AND DROP TABLE
ALTER TABLE EMPLOYEE
ADD COLUMN HIRED_DATE DATE;

ALTER TABLE EMPLOYEE
DROP COLUMN HIRED_DATE;

UPDATE EMPLOYEE
SET HIRED_DATE= "2023-09-11"
WHERE E_ID = 1;

UPDATE EMPLOYEE
SET HIRED_DATE= "2022-05-14"
WHERE E_ID = 2;

UPDATE EMPLOYEE
SET HIRED_DATE= "2020-01-08"
WHERE E_ID = 3;
UPDATE EMPLOYEE
SET HIRED_DATE= "2018-07-12"
WHERE E_ID = 4;
UPDATE EMPLOYEE
SET HIRED_DATE= "2015-07-23"
WHERE E_ID = 5;
UPDATE EMPLOYEE
SET HIRED_DATE= "2012-11-02"
WHERE E_ID = 4;
UPDATE EMPLOYEE
SET HIRED_DATE= "2021-01-22"
WHERE E_ID = 6;
UPDATE EMPLOYEE
SET HIRED_DATE= "2009-12-29"
WHERE E_ID = 7;
UPDATE EMPLOYEE
SET HIRED_DATE= "2001-05-31"
WHERE E_ID = 8;
UPDATE EMPLOYEE
SET HIRED_DATE= "2011-05-31"
WHERE E_ID = 9;
UPDATE EMPLOYEE
SET HIRED_DATE= "2017-03-30"
WHERE E_ID = 10;
UPDATE EMPLOYEE
SET HIRED_DATE= "2017-06-06"
WHERE E_ID = 11;
UPDATE EMPLOYEE
SET HIRED_DATE= "2015-03-12"
WHERE E_ID = 12;
UPDATE EMPLOYEE
SET HIRED_DATE= "2004-03-22"
WHERE E_ID = 13;
UPDATE EMPLOYEE
SET HIRED_DATE= "2006-11-07"
WHERE E_ID = 14;

SELECT * FROM EMPLOYEE
WHERE E_NAME REGEXP "SET";
SELECT * FROM EMPLOYEEcustomer
WHERE E_NAME REGEXP "^SET";
SELECT * FROM EMPLOYEE
WHERE E_NAME REGEXP "SH$";
SELECT * FROM EMPLOYEE
WHERE E_NAME REGEXP "SET|JI|NU";
SELECT * FROM EMPLOYEE
WHERE E_NAME REGEXP "S[RTU]";
SELECT * FROM EMPLOYEE
WHERE E_NAME REGEXP "V[EKOA]";
SELECT * FROM EMPLOYEE
WHERE E_NAME REGEXP "V[A-J]";