CREATE TABLE EMPLOYEE(
E_ID INT PRIMARY KEY,
E_NAME VARCHAR(30),
JOB_DESC VARCHAR(30),
SALARY INT
);

DROP TABLE EMPLOYEE;
SELECT* FROM EMPLOYEE;

CREATE TABLE EMPLOYEE(
E_ID INT PRIMARY KEY AUTO_INCREMENT,
E_NAME VARCHAR(30) NOT NULL,
JOB_DESC VARCHAR(30) DEFAULT "NOT DECIDED",
SALARY INT, 
PAN VARCHAR(30) UNIQUE 
);

INSERT INTO EMPLOYEE (E_NAME,SALARY,PAN) VALUES ("VIGNESH",25000,"ABCD12345");
INSERT INTO EMPLOYEE (E_NAME,SALARY,PAN) VALUES ("SATHISH",65000,"ABCD123763");

-- ADD NOT NULL CONSTRAINT
ALTER TABLE EMPLOYEE
MODIFY E_NAME VARCHAR(30) NOT NULL;

-- DROP NOT NULL CONSTRAINT
ALTER TABLE EMPLOYEE
MODIFY E_NAME VARCHAR(30);

-- ADD DEAFAULT CONATRAINT
ALTER TABLE EMPLOYEE
ALTER JOB_DESC SET DEFAULT "NOT DECIDED";

-- DROP DEFAULT CONSTRIANT
ALTER TABLE EMPLOYEE
ALTER JOB_DESC DROP DEFAULT;

-- ADD CHECK CONSTRAINT
ALTER TABLE EMPLOYEE
