-- AND OR NOT

SELECT * FROM EMPLOYEES
WHERE SALARY >=30000 AND E_NAME = "AJITH";

SELECT * FROM EMPLOYEES
WHERE NOT (SALARY >=30000 AND SALARY <= 60000);

SELECT * FROM EMPLOYEES
WHERE SALARY >=30000 AND E_NAME = "SURYA" OR E_ID = 3;

SELECT * FROM EMPLOYEES
WHERE SALARY >=30000 AND E_NAME IN ("SURYA","VIJAY","VIMAL") OR PH_NUMBER > 8897897899;

SELECT * FROM EMPLOYEES
WHERE SALARY >=55000 OR E_NAME = "VIJAY";

-- IN AND NOT IN
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IN ("HR","FINANCE");

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT NOT IN ("HR","FINANCE","CINIMA");