SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 30000 AND 75000;

-- AS TEMPORARY COLUMN NAME
SELECT E_NAME AS NAME, 
PH_NUMBER AS "PHONE NUMBER",
DEPARTMENT AS DPT 
FROM EMPLOYEES;

SELECT SALARY, SALARY * 12 AS YEARLY_SALARY FROM EMPLOYEES
WHERE SALARY >= 40000;