USE MCC;
DROP TABLE COLLEGE;
SELECT * FROM COLLEGE;
CREATE TABLE COLLEGE(
CLG_ID INT PRIMARY KEY,
LOCATION VARCHAR(30),
CLG_NAME VARCHAR(30));
INSERT INTO COLLEGE VALUES(1,"TAMBARAM","MADRAS CHRISTIAN COLLEGE");
INSERT INTO COLLEGE VALUES(2,"MEENAMBAKKAM","A M JAIN COLLEGE");
INSERT INTO COLLEGE VALUES(3,"NUNGAMBAKKAM","LOYOLA");
INSERT INTO COLLEGE VALUES(4,"TRICHY","BISHOP HEBER COLLEGE");
INSERT INTO COLLEGE VALUES(5,"GUINDY","ANNA UNIVERSITY");
INSERT INTO COLLEGE VALUES(6,"MADURAI","THE AMERICAN COLLEGE");
INSERT INTO COLLEGE VALUES(7,"KOVAI","KMC");
INSERT INTO COLLEGE VALUES(8,"DELHI","JN UNIVERSITY");