-- CONSTRAINTS
/*
NOT NULL - Column cannot have a NULL value
UNIQUE - All values in a column are different
PRIMARY KEY - A combination of a NOT NULL and UNIQUE
FOREIGN KEY - Prevents actions that would destroy links between tables
CHECK - Ensures that the values in a column satisfies a specific condition
DEFAULT - Sets a default value for a column if no value is specified
CREATE INDEX - Used to create and retrieve data from the database very quickly
*/
USE MY_COMPANY;

CREATE TABLE STUDENTS(
S_ID INT PRIMARY KEY AUTO_INCREMENT,
S_NAME VARCHAR(30) NOT NULL,
DEPARTMENT VARCHAR(30) DEFAULT "NOT ASSIGNED",
AADHAR VARCHAR(15) UNIQUE,
COURSE_FEES INT,
CHECK (COURSE_FEES>=15000)
);
DROP TABLE STUDENTS;

SELECT * FROM STUDENTS;

INSERT INTO STUDENTS (S_NAME,AADHAR,COURSE_FEES) VALUES ("DHONI",1234567890,25000); -- NO NEED TO GIVE S_ID ->> AUTO_INCREMENT
INSERT INTO STUDENTS (S_NAME,AADHAR,COURSE_FEES) VALUES ("KOHLI",1956780700,21000); -- NO NEED TO GIVE DEPARTMENT->> DEFAULT VALUES GIVEN

INSERT INTO STUDENTS (S_NAME,AADHAR,COURSE_FEES) VALUES ("YUVRAJ",8956180700,13000);-- CANNOT CA BE INSERTED ->> CHECK CONSTRAINT
INSERT INTO STUDENTS (AADHAR,COURSE_FEES) VALUES (9451180700,255000);-- CANNOT CA BE INSERTED ->> S_NAME SHOULD NOT HAVE NULL VALUES

INSERT INTO STUDENTS (S_NAME,AADHAR,COURSE_FEES) VALUES ("RAINA",1234567890,19000);-- CANNOT CA BE INSERTED->> AADHAR IS NOT UNIQUE
INSERT INTO STUDENTS (S_NAME,DEPARTMENT,AADHAR,COURSE_FEES) VALUES ("ROHIT","MI",5274567890,27000);

CREATE TABLE STUDENTS(
S_ID INT PRIMARY KEY,
S_NAME VARCHAR(30) ,
DEPARTMENT VARCHAR(30) ,
AADHAR VARCHAR(15) ,
COURSE_FEES INT
);

-- ADDING NOT NULL CONSTRAINT
ALTER TABLE STUDENTS
MODIFY S_NAME VARCHAR(30) NOT NULL;

-- DROPING NOT NULL CONSTRAINT
ALTER TABLE STUDENTS
MODIFY S_NAME VARCHAR(30);

-- ADDING DEFAULT CONSTRAINT
ALTER TABLE STUDENTS
ALTER DEPARTMENT SET DEFAULT "NOT ASSIGNED";

-- DROPING DEFAULT CONSTRAINT
ALTER TABLE STUDENT
ALTER DEPARTMENT DROP DEFAULT;

-- ADDING CHECK CONSTRAINT
ALTER TABLE STUDENTS
ADD CONSTRAINT CHECK_COURSE_FEES CHECK (COURSE_FEES>=15000);

-- DROPING CHECK CONSTRAINT
ALTER TABLE STUDENTS
DROP CONSTRAINT CHECK_COURSE_FEES;

-- AUTO INCREMENT
/*
CREATE TABLE COLLEGE (
CLASS_ID INT PRIMARY KEY AUTO_INCREMENT = 100 --> DEFAULT START POSITION 1
);


