-- DATATYPES

/*
NUMBERS
CHARACTER/STRING
DATE AND TIME
BOOLEAN
BINARY 


-- NUMBER
INT (WHOLE NUMBER) FROM -2,147,483,648 to 2,147,483,647
DECIMAL (P,S) LIKE DECIMAL (5,2) --> 5 NUMBER OF DIGIT AND 2 --> NUMBER OF DIGIT AFTER DECIMAL POINT

SMALLINT
BIGINT
FLOAT
DOUBLE


-- CHARACTER/STRING
CHAR() FIXED AND CAN BE STORED(0-255), 
VARCHAR() VARIABLE AND CAN BE STORED(0-255)
VARIABLE WITH NO SPECIFIC LIMIT

-- DATE AND TIME
DATE 2026-01-17
TIME 08:09:10
DATETIME/TIMESTAMP 2026-01-17 08:09:10

-- BOOLEAN
USED TO STORE TRUE OR FALSE VALUES

-- BINARY 
BINARY FIXED LENGTH BINARY DATA
VARBINARY VARIABLE LENGTH BINARY DATA
BLOB BINARY LARGE OBJECT --> TO STOR LARGE AMOUNT OF BINARY DATA
/*