-- TO DISPLAY EXISTING DATABASES
SHOW DATABASES;

-- CREATING DATABASE,  WE CAN USE SCHEMA FOR DATABASE
CREATE DATABASE MY_COMPANY;

-- USE USED TO CHOOSE THE DATABASE 
USE MY_COMPANY;

-- DROP DATABASE OR SCHEMA
DROP DATABASE MY_COMPANY;

-- TABLE
-- TO DISPLAY EXISTING TABLES
SHOW TABLES;
CREATE TABLE EMPLOYEES (
E_ID INT PRIMARY KEY,
E_NAME VARCHAR(30),
DEPARTMENT VARCHAR (30),
SALARY DECIMAL(7,2),
EMAIL VARCHAR(30),
PH_NUMBER VARCHAR(10)
);
-- TO READ TO THE TABLE USE SELECT QUERY 
SELECT * FROM EMPLOYEES;

-- DROP TABLE
DROP TABLE EMPLOYESS;

-- TO ADD A NEW COLUMN
ALTER TABLE EMPLOYEES ADD BRANCH_ID VARCHAR (2);

-- TO DROP A COLUMN
ALTER TABLE EMPLOYEES DROP BRANCH_ID;

ALTER TABLE EMPLOYEES
MODIFY SALARY DECIMAL(7,0);

ALTER TABLE EMPLOYEES
DROP EMAIL;

ALTER TABLE EMPLOYEES
DROP PH_NUMBER; 

CREATE TABLE BRANCH ( 
B_ID INT PRIMARY KEY,
B_NAME VARCHAR(20),
STATE VARCHAR(20)
);

INSERT INTO BRANCH VALUES(1,"CHENNAI","TAMIL NADU"),
(2,"BANGALORE","KARNATAKA"),
(3,"MUMBAI","MAHARASTRA"),
(4,"HYDRABAD","TELANGANA"),
(5,"DELHI","DELHI")
;
SELECT * FROM BRANCH;

ALTER TABLE EMPLOYEES
ADD COLUMN B_ID INT;
