-- GROUP BY
SELECT * FROM EMPLOYEES;
SELECT DEPARTMENT, ROUND(AVG(SALARY),0) AS "AVG SALARY"
FROM EMPLOYEES 
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, COUNT(E_ID) FROM 
EMPLOYEES
GROUP BY DEPARTMENT;

-- HAVING (FILTER GROUPS) BUT WHERE IS USE TO FILTER RECORDS
SELECT DEPARTMENT, COUNT(E_ID) FROM 
EMPLOYEES
GROUP BY DEPARTMENT
HAVING COUNT(E_ID)>1
ORDER BY DEPARTMENT;

SELECT DEPARTMENT, COUNT(E_ID)
FROM EMPLOYEES
WHERE SALARY >30000
GROUP BY DEPARTMENT
HAVING COUNT(E_ID)>1
ORDER BY DEPARTMENT;

SELECT DEPARTMENT , AVG(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING AVG(SALARY) >=35000;
