SELECT * FROM STUDENTS;
SELECT * FROM COLLEGE;

SELECT S.ID, S.NAME, S.DEPARTMENT, C.CLG_NAME
FROM STUDENTS AS S
INNER JOIN COLLEGE AS C
ON  S.CLG_ID = C.CLG_ID;

SELECT S.ID, S.NAME, S.DEPARTMENT, C.CLG_NAME
FROM STUDENTS AS S
LEFT JOIN COLLEGE AS C
ON  S.CLG_ID = C.CLG_ID;

SELECT S.ID, S.NAME, S.DEPARTMENT, C.CLG_NAME
FROM STUDENTS AS S
RIGHT JOIN COLLEGE AS C
ON  S.CLG_ID = C.CLG_ID;

SELECT S.ID, S.NAME, S.DEPARTMENT, C.CLG_NAME
FROM STUDENTS AS S
CROSS JOIN COLLEGE AS C;

SELECT C.CLG_NAME, COUNT(S.ID) TOTAL
FROM COLLEGE AS C
JOIN STUDENTS AS S
ON C.CLG_ID = S.CLG_ID
GROUP BY S.CLG_ID;

