-- JOINS
SELECT * FROM EMPLOYEES;
SELECT * FROM BRANCH;
-- INNER JOINS
SELECT E.E_NAME, E.DEPARTMENT,B.B_NAME
FROM EMPLOYEES AS E
INNER JOIN BRANCH AS B
ON E.B_ID = B.B_ID;

-- LEFT JOINS
SELECT E.E_NAME, E.DEPARTMENT,B.B_NAME
FROM EMPLOYEES AS E
LEFT JOIN BRANCH AS B
ON E.B_ID = B.B_ID;

-- RIGHT JOINS
SELECT E.E_NAME, E.DEPARTMENT,B.B_NAME
FROM EMPLOYEES AS E
RIGHT JOIN BRANCH AS B
ON E.B_ID = B.B_ID;

-- CROSS JOINS
SELECT E.E_NAME, E.DEPARTMENT,B.B_NAME
FROM EMPLOYEES AS E
CROSS JOIN BRANCH AS B
ON E.B_ID = B.B_ID;
-- UNON AND UNION ALL
-- NUMBER OF COLUMNS SHOULD MATCH TO GET OUTPUT 
-- UNION GAVE MATCHED RESULT ONLY WHEREAS UNION ALL GIVE ALL THE RECORDS
SELECT * FROM EMPLOYEES
UNION
SELECT * FROM BRANCH;