CREATE DATABASE MCC;
USE MCC;
CREATE TABLE students(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(30),
M1 INT,
M2 INT,
M3 INT,
SALARY INT,
CGPA DECIMAL(5,2)
);
INSERT INTO STUDENTS VALUES(1,"VIGNESH",70, 90,66,25000, 8.6,"BOOKINGS",1);
INSERT INTO STUDENTS VALUES(11,"DIVYA",99, 90,88,40000, 9.6,"HR",1);
INSERT INTO STUDENTS VALUES(12,"SANTHOSH",79, 91,76,38000, 8.6,"TAX_ANALYST",2);
INSERT INTO STUDENTS VALUES(13,"PAVITHRA",60, 80,63,40000, 7.6,"OPERATION",1);
INSERT INTO STUDENTS VALUES(14,"BEULAH",90, 90,96,450000, 9.9,"FINANCE",3);
INSERT INTO STUDENTS VALUES(2,"GURU",60, 80,79,39000, 8.4,"TAX_ANALYST",3);
INSERT INTO STUDENTS VALUES(3,"ARUN",80, 90,55,30000, 7.6,"TEACHER",3);
INSERT INTO STUDENTS VALUES(4,"BIBIN",80, 90,95,32000, 9.6,"TECHNICAL",1);
INSERT INTO STUDENTS VALUES(5,"DINESH",60, 77,85,31000, 8.6,"TEACHER",1);
INSERT INTO STUDENTS VALUES(6,"VIJAY",80, 80,95,40000, 9.6,"TEACHER",1);
INSERT INTO STUDENTS VALUES(7,"YASAR",69, 71,59,33000, 6.5,"BOOKINGS",2);
INSERT INTO STUDENTS VALUES(8,"THEODER",69, 91,78,50000, 7.6,"LEAD",3);
INSERT INTO STUDENTS VALUES(9,"NILAVER",78, 81,66,34000, 8.2,"BOOKINGS",4);
INSERT INTO STUDENTS VALUES(10,"MANIKANDAN",77, 66,88,29000, 7.2,"BOOKINGS",5);

SELECT * FROM STUDENTS;
DESCRIBE STUDENTS;
DROP TABLE STUDENTS;
ALTER TABLE STUDENTS ADD DEPARTMENT VARCHAR(20);
ALTER TABLE STUDENTS DROP DEPARTMENT;
ALTER TABLE STUDENTS ADD CLG_ID INT;

SELECT DISTINCT DEPARTMENT FROM STUDENTS;

SELECT * FROM STUDENTS
WHERE ID = 11;

SELECT * FROM STUDENTS 
WHERE NAME = "VIGNESH";

SELECT * FROM STUDENTS
WHERE DEPARTMENT  = "TEACHER";

SELECT * FROM STUDENTS
WHERE DEPARTMENT  != "TEACHER";

SELECT * FROM STUDENTS
WHERE DEPARTMENT  <> "TEACHER";
-- USING IN AND NOT IN
SELECT * FROM STUDENTS
WHERE DEPARTMENT IN ("TAX_ANALYST","FINANCE");

SELECT * FROM STUDENTS
WHERE DEPARTMENT  NOT IN ("BOOKINGS","TEACHER");

SELECT * FROM STUDENTS
WHERE M1 IN (80,80);

SELECT * FROM STUDENTS 
WHERE CLG_ID = 1;

SELECT * FROM STUDENTS
WHERE M1 >85;

SELECT * FROM STUDENTS
WHERE M1 >60;
SELECT * FROM STUDENTS
WHERE M1 >70 AND M2 > 80 AND M3 >74;

SELECT * FROM STUDENTS
WHERE M1 >90 OR M2 > 80 OR M3 >94;

SELECT * FROM STUDENTS
WHERE M1 >90 AND M2 > 80 OR M3 >94;

SELECT * FROM STUDENTS
WHERE M1 BETWEEN 75 AND 90;

SELECT * FROM STUDENTS
WHERE CGPA >9;

SELECT NAME, DEPARTMENT 
FROM STUDENTS;
-- PROVIDING DATA TO A SPECIFIC COLUMN ALONE, REST OF THE DATA WILL STORE AS NULL
INSERT INTO STUDENTS (ID, NAME, DEPARTMENT) VALUES(15,"RAJ","FRRELANCER");

SELECT * FROM STUDENTS;

SELECT * FROM STUDENTS
ORDER BY NAME;

SELECT * FROM STUDENTS
ORDER BY NAME, CGPA;

SELECT * FROM STUDENTS
ORDER BY DEPARTMENT, NAME;


SELECT * FROM STUDENTS
LIMIT 5;

-- LIKE AND WILDCARD
-- NAME SHOULD BE START WITH S AND THEN ANYTHING CAN BE THERE
SELECT * FROM STUDENTS
WHERE NAME LIKE "S%";

-- NAME SHOULD BE END WITH H AND BEFORE ANYTHING CAN BE THERE
SELECT * FROM STUDENTS
WHERE NAME LIKE "%H";

-- NAME SHOULD BE START WITH B AND END WITH H AND INBETWEEN ANYTHING CAN BE THERE
SELECT * FROM STUDENTS
WHERE NAME LIKE "B%H";

-- NAME SHOULD BE START WITH V AND END WITH H AND INBETWEEN I SHOULD BE THERE
SELECT * FROM STUDENTS
WHERE NAME LIKE "V%I%H";

SELECT * FROM STUDENTS
WHERE NAME NOT LIKE "V%I%H";

-- 3RD LETTER SHOULD BE J AFTER THAT ANYTHING CAN BE THERE
SELECT * FROM STUDENTS
WHERE NAME LIKE "__J%";

SELECT * FROM STUDENTS
WHERE NAME LIKE "__J%" AND NAME LIKE "B%H";

SELECT * FROM STUDENTS
WHERE NAME LIKE "__J%" OR NAME LIKE "B%H";

-- NAME SHOULD BE START WITH S AND ANY CHARECTER AND THEN J
SELECT * FROM STUDENTS
WHERE NAME LIKE "R%_J%";

ALTER TABLE STUDENTS ADD SALARY INT;

SELECT * FROM STUDENTS;
INSERT INTO STUDENTS (SALARY) VALUES(25000);

UPDATE STUDENTS
SET SALARY = NULL
WHERE SALARY = 25000;

DELETE FROM STUDENTS 
WHERE ID = 16;

UPDATE  STUDENTS
SET SALARY = 20000
WHERE ID = 15;

SELECT NAME, SALARY FROM STUDENTS
ORDER BY SALARY DESC;

SELECT NAME, SALARY FROM STUDENTS
ORDER BY SALARY,NAME DESC;

-- USING CASE IN ORDER BY 

SELECT * FROM STUDENTS
ORDER BY (CASE DEPARTMENT
WHEN "OPERATION" THEN 1
WHEN "TECHNICAL" THEN 2
WHEN "BOOKINGS" THEN 3
WHEN "HR" THEN 5
WHEN "TEACHER" THEN 6
ELSE 100 END
),NAME;