SELECT * FROM EMPLOYEES
ORDER BY E_ID DESC;

SELECT * FROM EMPLOYEES
ORDER BY E_NAME;

SELECT * FROM EMPLOYEES
ORDER BY SALARY;

SELECT * FROM EMPLOYEES
ORDER BY E_NAME, SALARY;

SELECT * FROM EMPLOYEES
ORDER BY DEPARTMENT DESC, SALARY;SSS

SELECT * FROM EMPLOYEES
LIMIT 4;

SELECT * FROM EMPLOYEES
LIMIT 4,3;-- SKIPS FIRST 4 AND 3 RECORDS AFTER 4