create database Amazon;
use Amazon;
create table customer(
E_ID int primary key,
E_name varchar(20),
E_JD varchar(30),
E_PN int
);
DROP TABLE CUSTOMER;
SELECT * FROM CUSTOMER;
ALTER TABLE CUSTOMER
MODIFY E_NAME VARCHAR(30) NOT NULL;
ALTER TABLE CUSTOMER
MODIFY E_NAME VARCHAR(30);

ALTER TABLE CUSTOMER
ALTER E_JD SET default 'UNASSIGNED';

ALTER TABLE CUSTOMER
ALTER E_JD DROP defaulT;

ALTER TABLE CUSTOMER
ADD constraint VICKY CHECK (E_PN>3444);
ALTER TABLE CUSTOMER
DROP CONSTRAINT VICKY;

ALTER TABLE CUSTOMER
ADD constraint ABC UNIQUE(E_PN);

ALTER TABLE CUSTOMER
DROP CONSTRAINT ABC;

ALTER TABLE CUSTOMER
ADD CONSTRAINT E_DEF CHECK (E_PN >1);

ALTER TABLE CUSTOMER
ADD SALARY INT NOT NULL;







