-- PRIMARY & FOREING KEY
CREATE DATABASE VIGNESH;
USE VIGNESH;
CREATE TABLE BRANCH ( 
B_ID INT PRIMARY KEY,
B_NAME VARCHAR(20),
STATE VARCHAR(20)
);

CREATE TABLE EMPLOYEES (
E_ID INT PRIMARY KEY,
E_NAME VARCHAR(30),
DEPARTMENT VARCHAR (30),
SALARY DECIMAL(7,2),
B_ID INT,
CONSTRAINT FK_B_ID FOREIGN KEY (B_ID) REFERENCES BRANCH(B_ID)
);
SELECT * FROM EMPLOYEES;
SELECT * FROM BRANCH;

-- CANNOT DROP BRANCH TABLE BECAUSE EMPLOYEES TABLE REFERENCES THE BRANCH TABLE
-- WE CAN DROP EMPLOYEES TABLE BEFORE DROPPING BRANCH TABLE TO AVOID ERRORS

-- DROPPING FOREIGN KEY CONSTRAINT
ALTER TABLE EMPLOYEES
DROP FOREIGN KEY FK_B_ID; -- ONLY DROP LINK BETWEEN TWO TABLES NOT THE COLUMN

 -- NOW WE CAN DROP BRANCH TABLE 
 
 