-- REGEXP

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT REGEXP "HR"; 

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT REGEXP "KET"; 

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT REGEXP "^POL"; 

SELECT * FROM EMPLOYEES
WHERE E_NAME REGEXP "USH$"; 

SELECT * FROM EMPLOYEES
WHERE E_NAME REGEXP "NAN|KET|TIS"; 

SELECT * FROM EMPLOYEES
WHERE E_NAME REGEXP "^VI|EP$|YA"; 

SELECT * FROM EMPLOYEES
WHERE E_NAME REGEXP "I[TVK]"; 

SELECT * FROM EMPLOYEES
WHERE E_NAME REGEXP "[MVR]A"; 

SELECT * FROM EMPLOYEES
WHERE E_NAME REGEXP "[P-V]A"; 

/* NOTE
^ BEGINNING
$ END
| LOGICAL OR
[A]B 
[A-F] R
*/