-- TO SELECT ALL THE COLUMN HAVE TO USE *
SELECT * FROM EMPLOYEES;

-- TO SELECT SPECIFIC COLUMN
SELECT E_ID, E_NAME,DEPARTMENT FROM EMPLOYEES;

-- WHERE
SELECT * FROM EMPLOYEES
WHERE E_NAME = "AJITH";

SELECT * FROM EMPLOYEES
WHERE E_ID= 7;

SELECT * FROM EMPLOYEES
WHERE E_NAME != "VIGNESH";

SELECT * FROM EMPLOYEES
WHERE E_NAME <> "VIGNESH";

SELECT * FROM EMPLOYEES
WHERE SALARY >=35000;

SELECT * FROM EMPLOYEES
WHERE SALARY <25000;

SELECT * FROM EMPLOYEES
WHERE SALARY >=45000 AND E_NAME = "RAJINI";

SELECT * FROM EMPLOYEES
WHERE SALARY >=55000 OR E_NAME = "VIJAY";

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT IN ("HR","FINANCE");

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT NOT IN ("HR","FINANCE","CINIMA");