-- AGGREGATE FUNCTION
USE MCC;
SELECT * FROM STUDENTS;
UPDATE STUDENTS 
SET SALARY = 45000
WHERE ID = 14;

UPDATE STUDENTS 
SET DEPARTMENT = "TNPSC"
WHERE ID = 15;
SELECT COUNT(*) AS COUNT_STUDENT FROM STUDENTS;

SELECT COUNT(*) FROM STUDENTS
WHERE DEPARTMENT  = "BOOKINGS";

SELECT AVG(SALARY) FROM STUDENTS;
SELECT MIN(SALARY) FROM STUDENTS;
SELECT MAX(SALARY) FROM STUDENTS;
SELECT SUM(SALARY) FROM STUDENTS;

-- STRING FUNCTION

SELECT UCASE(DEPARTMENT) FROM STUDENTS;

SELECT DEPARTMENT,CHAR_LENGTH(DEPARTMENT) AS LENGTH FROM STUDENTS;

SELECT SALARY, CONCAT("RS.", SALARY) AS SALARY FROM STUDENTS;

SELECT SALARY, CONCAT("RS.", FORMAT(SALARY,0)) AS SALARY FROM STUDENTS;

-- SELECT NAME, CONCAT("MR/MRS. ",NAME) AS NAME FROM STUDENTS;

SELECT DEPARTMENT, AVG(SALARY)FROM STUDENTS
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, COUNT(ID) FROM STUDENTS
GROUP BY DEPARTMENT;

SELECT DEPARTMENT, COUNT(ID) FROM STUDENTS
GROUP BY DEPARTMENT
HAVING COUNT(ID) >= 1
ORDER BY DEPARTMENT DESC;

SELECT DEPARTMENT, AVG(SALARY) FROM STUDENTS
GROUP BY DEPARTMENT
HAVING  AVG(SALARY)> 30000;

SELECT * FROM STUDENTS;