USE MY_COMPANY;
-- SUBQUERY ==> QUERY INSIDE QUERY

SELECT * FROM EMPLOYEES;
SELECT * FROM BRANCH;

SELECT E_NAME, DEPARTMENT, B_ID FROM EMPLOYEES
WHERE B_ID = (SELECT B_ID FROM BRANCH WHERE B_NAME = "BANGALORE");

SELECT * FROM EMPLOYEES
WHERE SALARY =(SELECT MIN(SALARY) FROM EMPLOYEES);

