-- LIKE AND WILDCARD

-- % 0 OR MORE CHARACTER
SELECT * FROM EMPLOYEES
WHERE E_NAME LIKE "V%"; -- E_NAME SHOULD BE START WITH V AND THEN ANYTHING CAN BE THERE

SELECT * FROM EMPLOYEES
WHERE E_NAME LIKE "%I"; -- E_NAME SHOULD END WITH I AND BEFORE ANYTHING CAN BE THERE

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT LIKE "%KET%"; 

SELECT * FROM EMPLOYEES
WHERE E_NAME LIKE "S%N"; -- E_NAME MUST START WITH S AND ENDS WITH N

SELECT * FROM EMPLOYEES
WHERE E_NAME LIKE "P%D%P"; -- E_NAME MUST START WITH P AND ENDS WITH P INBETWEEN D 

-- _ SINGLE CHARACTER
SELECT * FROM EMPLOYEES
WHERE E_NAME LIKE "_I%"; -- 2ND CHARACTER MUST START WITH I AND THEN ANYTHING CAN BE THERE

SELECT * FROM EMPLOYEES
WHERE E_NAME LIKE "_I%" AND DEPARTMENT LIKE "%G";

SELECT * FROM EMPLOYEES
WHERE E_NAME LIKE "_I%" OR DEPARTMENT LIKE "%G";

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT LIKE "F__A%";
